@startuml
skinparam style strictuml
skinparam classAttributeIconSize 0

class Student {
  - studentID: int
  - name: String
  - course: String
  + enroll()
}

class Course {
  - courseID: int
  - courseName: String
}

Student "0..*" --> "20..40" Course : enrolls
@enduml
